CREATE DATABASE IF NOT EXISTS GARDENDB;
USE GARDENDB;
CREATE TABLE IF NOT EXISTS status (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    moistness FLOAT NOT NULL,
    water_level FLOAT NOT NULL,
    time_stamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
